### ISSUE TITLE
file name too long in set_owner_if_different().

### ISSUE THREAD

**Issue by maspotts** [geerlingguy/ansible-collection-mac#107] opened 2024-06-01 16:24 UTC
### Discussed in https://github.com/geerlingguy/ansible-collection-mac/discussions/106

<div type='discussions-op-text'>

<sup>Originally posted by **maspotts** June  1, 2024</sup>
Turns out I do have a problem: it looks like some kind of recursive path building algorithm might be failing to terminate here?

```
TASK [geerlingguy.mac.homebrew : Ensure proper ownership on homebrew_install_path subdirs.] **********************************************************************************************************************************************************************************
fatal: [ponyo]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.1.75 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/Users/mike/.ansible/tmp/ansible-tmp-1717250822.494478-65710-100679503069128/AnsiballZ_file.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/Users/mike/.ansible/tmp/ansible-tmp-1717250822.494478-65710-100679503069128/AnsiballZ_file.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/Users/mike/.ansible/tmp/ansible-tmp-1717250822.494478-65710-100679503069128/AnsiballZ_file.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\r\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/modules/file.py\", line 987, in <module>\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/modules/file.py\", line 973, in main\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/modules/file.py\", line 683, in ensure_directory\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/modules/file.py\", line 369, in recursive_set_attributes\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/modules/file.py\", line 369, in recursive_set_attributes\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/modules/file.py\", line 369, in recursive_set_attributes\r\n  [Previous line repeated 17 more times]\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/modules/file.py\", line 353, in recursive_set_attributes\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/module_utils/basic.py\", line 1153, in set_fs_attributes_if_different\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/module_utils/basic.py\", line 797, in set_owner_if_different\r\n  File \"/tmp/ansible_file_payload_c9fv2vri/ansible_file_payload.zip/ansible/module_utils/basic.py\", line 691, in user_and_group\r\nOSError: [Errno 63] File name too long: b'/Applications/calibre.app/Contents/ebook-viewer.app/Contents/../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../QtWebEngineCore.framework/QtWebEngineCore'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
</div>

**Comment by kdkasad** [comment] 2024-07-16 06:24
I am also encountering this issue. It's with a different app, but also contains Qt directories.

Full error output and traceback:
```
TASK [geerlingguy.mac.homebrew : Ensure proper ownership on homebrew_install_path subdirs.] ****
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 63] File name too long: b'/Applications/Jellyfin Media Player.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/libqtquickcontrols2universalstyleplugin.dylib'
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/Users/kian/.ansible/tmp/ansible-tmp-1721110717.653553-54709-125912665711346/AnsiballZ_file.py", line 107, in <module>
    _ansiballz_main()
  File "/Users/kian/.ansible/tmp/ansible-tmp-1721110717.653553-54709-125912665711346/AnsiballZ_file.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/kian/.ansible/tmp/ansible-tmp-1721110717.653553-54709-125912665711346/AnsiballZ_file.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/modules/file.py", line 988, in <module>
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/modules/file.py", line 974, in main
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/modules/file.py", line 684, in ensure_directory
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/modules/file.py", line 370, in recursive_set_attributes
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/modules/file.py", line 370, in recursive_set_attributes
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/modules/file.py", line 370, in recursive_set_attributes
  [Previous line repeated 14 more times]
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/modules/file.py", line 354, in recursive_set_attributes
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1094, in set_fs_attributes_if_different
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/module_utils/basic.py", line 738, in set_owner_if_different
  File "/tmp/ansible_file_payload_iocsp9xm/ansible_file_payload.zip/ansible/module_utils/basic.py", line 632, in user_and_group
OSError: [Errno 63] File name too long: b'/Applications/Jellyfin Media Player.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/../../../../../../../Frameworks/libqtquickcontrols2universalstyleplugin.dylib'
```

**Comment by kdkasad** [comment] 2024-07-31 05:41
More information on this problem: It looks like the issue is caused because some Cask applications contain symlink cycles.

[One of the tasks](https://github.com/geerlingguy/ansible-collection-mac/blob/7f5765b5eeb005a0f4e772e54b59d04240aae3e4/roles/homebrew/tasks/main.yml#L72) in the `homebrew` role recursively sets permissions on `/opt/homebrew`.
However, this also follows symbolic links to directories outside of `/opt/homebrew`. For example, all casks link to the installed app contents:
```
$ ls -lah /opt/homebrew/Caskroom/firefox/128.0.3
total 4.0K
drwxr-xr-x 4 kian staff 128 Jul 30 22:26 .
drwxr-xr-x 4 kian staff 128 Jul 30 22:26 ..
lrwxr-xr-x 1 kian staff  25 Jul 30 22:26 Firefox.app -> /Applications/Firefox.app
-rwxr-xr-x 1 kian staff  73 Jul 30 22:26 firefox.wrapper.sh
```

This is what's causing the issue, as some casks (not the Firefox one exemplified above) contain cyclic directory structures. But it seems to me like we shouldn't be touching files outside of `/opt/homebrew`, especially not in the `/Applications` directory, as it's possible some app contents require special permissions.

I believe this would be fixed by simply providing `follow: false` to the task linked above. I'll open a PR with this change.

**Closed** 2024-08-11 02:33 UTC
